# Cloud Build configuration for portfolio app
# Builds and pushes Docker image to Artifact Registry

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--tag'
      - '${_IMAGE_URI}'
      - '.'
    id: 'build-image'

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_IMAGE_URI}'
    id: 'push-image'

# Substitution variables (passed from GitHub Actions)
substitutions:
  _IMAGE_URI: '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/${_IMAGE_NAME}:${_TAG}'

# Build options
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
