name: Build and Deploy to Cloud Run

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  PROJECT_ID: me2u-prj-app-prod-3aa8
  REGION: us-central1
  SERVICE: me2u-cloudrun-app-750162622024
  REPOSITORY: me2u-artifact-docker
  IMAGE: me2u

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure gcloud project
        run: |
          gcloud config set project ${{ env.PROJECT_ID }}
          gcloud config list

      - name: Build Docker image
        run: |
          gcloud builds submit \
            --project=${{ env.PROJECT_ID }} \
            --tag us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE }} \
            --image us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:latest \
            --region ${{ env.REGION }} \
            --project ${{ env.PROJECT_ID }} \
            --platform managed \
            --allow-unauthenticated